<?php

/**
 * @file
 * Contains d8_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_form module.
    case 'help.page.d8_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is study case for form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8_form_theme() {
  $theme = [];

  return $theme;
}
