<?php

/**
 * @file
 * Contains d8_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function d8_form_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_form module.
    case 'help.page.d8_form':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is study case for form') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8_form_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_form_alter().
 */
function d8_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $hide = \Drupal::config('d8_form.simple_config')->get('hide_alter');
  if (!$hide) {
    $form['alter_message'] = array(
      '#type' => 'markup',
      '#markup' => t('!form_id: Form is altered by !module', array('!form_id' => $form_id, '!module' => 'd8_form')),
      '#prefix' => '<div class="messages messages--error">',
      '#suffix' => '</div>',
      '#weight' => -100
    );
    
    $form['#validate'][] = 'd8_form_validate_callback';
    $form['#submit'][] = 'd8_form_submit_callback';
  }
}

/**
 * Form validate callback
 * @param type $form
 * @param FormStateInterface $form_state
 */
function d8_form_validate_callback($form, FormStateInterface $form_state) {
  drupal_set_message('validate:' . __FUNCTION__);
}

/**
 * Form submit callback
 * @param type $form
 * @param FormStateInterface $form_state
 */
function d8_form_submit_callback($form, FormStateInterface $form_state) {
  drupal_set_message('submit:' . __FUNCTION__);
}

// For the other way we can use form_FORM_ID_alter().